name: Terraform Validate

on:
  workflow_dispatch:

#env:
#  TF_ROOT: "terraform/**"

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    env: 
      TF_VAR_my_ip: ${{ secrets.MY_IP }}
    
    defaults:
      run:
        working-directory: ./terraform
#    env:
#      TF_VERSION: '1.0.0'  # Set the Terraform version
#      TF_ROOT: '.'  # Directory of your Terraform root configuration

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-southeast-2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate
#      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan
#      working-directory: ./terraform
